package com.example.linuxapp.ui.notification

class ConstantNotifications {
    val RECEIVE_NOTIFICATIONS =  "COM.EXAMPLE.TIME_NOTIFIER.RECEIVE_NOTIFICATIONS"
    val RECEIVE_AT_NIGHT = "COM.EXAMPLE.TIME_NOTIFIER.RECEIVE_AT_NIGHT"
    val NIGHT_TIME_START = "COM.EXAMPLE.TIME_NOTIFIER.NIGHT_TIME_START"
    val NIGHT_TIME_END = "COM.EXAMPLE.TIME_NOTIFIER.NIGHT_TIME_END"
    val NOTIFICATION_PERIOD = "COM.EXAMPLE.TIME_NOTIFIER.NOTIFICATION_PERIOD"
    val NOTIFICATION_TEXT = "COM.EXAMPLE.TIME_NOTIFIER.NOTIFICATION_TEXT"
}